import Head from 'next/head';
import { Menu } from '@/componentes/Menu';

export default function Home() {
  return (
    <>
      <Head>
        <title>Loja Next</title>
         <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Menu />
        <main className="container" >
          <h1 className='my-3'>Página Inicial</h1>
        </main>
    </>
  );
}
