import { Menu } from '@/componentes/Menu';
import type { NextPage } from 'next';
import { useState, useEffect } from 'react';
import Livro from '@/classes/modelo/Livro';
import Head from 'next/head';
import { LinhaLivro } from '@/componentes/LinhaLivro';
import ControleLivro from '@/classes/controle/ControleLivros';

const controleLivros = new ControleLivro()

const LivroLista: NextPage = () => {
  const [livros, setLivros] = useState<Array<Livro>>([]);
  const [carregado, setCarregado] = useState<boolean>(false);

  useEffect(() => {
    controleLivros.obterLivros().then((resultado: any) => {
      setLivros(resultado);
      setCarregado(true);
    });
  }, [carregado]);

  const excluir = async (codigo: string) => {
    await controleLivros.excluir(codigo).then(()=>{
      setCarregado(false);
    })
  };
  return (
    <>
      <Menu />
        <Head>
          <title>Loja Next</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>

        <main className="container">
          <h1 className='my-3'>Catálogo de Livros</h1>
          <table className="table table-success table-striped">
            <thead>
              <tr className=" table-dark">
                <th>Título</th>
                <th>Resumo</th>
                <th>Editora</th>
                <th>Autores</th>
              </tr>
            </thead>
            <tbody>
              {livros.map((livro, index) => (
                <LinhaLivro
                  key={index}
                  livro={livro}
                  excluir={excluir}
                />
              ))}
            </tbody>
          </table>
        </main>
    </>
  );
};

export default LivroLista;
